---
# tasks file for node_deploy
  - name: "Open the firewall ports for the specific application deployment"
    include: open_http_firewall.yaml

  - name: "Install Apache"
    include: install_apache.yaml

  - name: "Copy website over"
    include: install_apache.yaml
